config/routes.rb
Rails.application.routes.draw do
  get 'payments/new'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  resources :users, only: [:show, :edit, :update, :destroy] 

  resources :listings do

  resources :reservations, only: [:create , :show]
end
  resources :reservations, only: [] do
    resources :payments, only: [:new, :create]
  end

  

  root 'welcome#index'

end

app/models/listing.rb
class Listing < ActiveRecord::Base

    mount_uploaders :photos, PhotoUploader

	belongs_to :user
	has_many :reservations

	def mine?(user)
		if user.nil?
			return false
		else
			return self.user_id == user.id
		end
	end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
	def index
		@user = current_user
		
		if @user.role == "landlord"
			@listings = Listing.where(user_id: current_user.id)
			@listings = @listings.paginate(:page => params[:page], :per_page => 5)
		else
			@listings = Listing.all
			@listings = @listings.paginate(:page => params[:page], :per_page => 5)		
		end
	end

	def show

		
		@listing = Listing.find(params[:id])
	end

	def new
		@listing = Listing.new
	end

	def create
		@listing = current_user.listings.new(listing_params)
		if @listing.save
			redirect_to @listing
		else
			render 'new'
		end
	end

	def edit
		@listing = Listing.find(params[:id])
	end

	def update
		@listing = Listing.find(params[:id])
		if @listing.update(listing_params)
			redirect_to @listing, notice: "Success!"
		else 
			render 'edit'
		end
	end

	def destroy
		Listing.find(params[:id]).destroy
		redirect_to root_path
	end

	private

	def listing_params
		params.require(:listing).permit(:property_name, :country, :city_town, :home_type, :guest, :description, :price, {photos: []})
	end
end

app/views/listings/_form.html.erb
<%= form_for @listing do |f| %>
  <%= f.label :property_name %>:
  <%= f.text_field :property_name %><br />

  <%= f.label :country %>:
  <%= f.text_field :country %><br />

  <%= f.label :city_town %>:
  <%= f.text_field :city_town %><br />

  <%= f.label :home_type %>:
  <%= f.text_field :home_type %><br />

  <%= f.label :guest %>:
  <%= f.text_field :guest %><br />

  <%= f.label :description %>:
  <%= f.text_field :description %><br />

  <%= f.label :price %>:
  <%= f.text_field :price %><br />

  <%= f.file_field :photos, multiple: true %><br />

  <%= f.submit %>
<% end %>

app/views/listings/edit.html.erb
<h1>Edit Listing</h1>

<%= render 'form' %>

app/views/listings/index.html.erb
<h1>Listings</h1>

<% if @user.role == "superadmin" || @user.role == "landlord" %>
<%= link_to "Add a new listing", new_listing_path %>
<% end %>

<table>
	<thead>
		<tr>
			<th>No</th>
			<th>Images</th>
			<th>Property_name</th>
			<th>Country</th>
			<th>City/Town</th>
			<th>Home_type</th>
			<th>Guest_no</th>
			<th>Description</th>
			<th>Price</th>
		</tr>
	</thead>
	<tbody>
	<% @listings.each.with_index(1) do |listing, index| %>
		<tr>
		    <td><%= "*" if listing.mine?(current_user) %><%= index %></td>
        <td>
          <% if !listing.photos.empty? %>
            <%= image_tag listing.photos.first.thumb.url %>
          <% end %>
        </td>
			<!-- <td>< %= "*" if listing.mine?(current_user) %>< %= index %></td> -->
			<td><%= link_to listing.property_name, listing_path(listing.id) %></td>
			<td><%= listing.country %></td>
			<td><%= listing.city_town %></td>
			<td><%= listing.home_type %></td>
			<td><%= listing.guest %></td>
			<td><%= listing.description %></td>
			<td><%= listing.price %></td>
			<td><%= "#" if listing.reservations.any? %></td>
		</tr>
		<% end %>
	</tbody>
</table>

<%= will_paginate @listings %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form' %>

app/views/listings/show.html.erb
<h1>We Are Glad You clicked on Us!</h1>

<% @listing.photos.each do |photos| %>
<%= image_tag photos.thumb.url %>
<% end %>

<% if @listing.mine?(current_user) %>
<%= link_to "Edit listing", edit_listing_path(@listing) %>
<%= link_to "Delete Listing", listing_path(@listing), method: :delete, data: {:confirm => 'Are you sure?'} %>
<% end %>

<h2><%= @listing.property_name %></h2>
	<h3>Country: <%= @listing.country %></h3>
	<h3>City/Town: <%= @listing.city_town %></h3>
	<h3>Home type: <%= @listing.home_type %></h3>
	<h3>No. of guests: <%= @listing.guest %></h3>
	<h3>Description : <%= @listing.description %></h3>
	<h3>Price (negotiable) : <%= @listing.price %></h3>

    <% if signed_in? %>    
		<%= render 'reservations/form' %>
	<% else %>
	<p>Please <%= link_to "Sign in", sign_in_path %> to make a reservation</p>
	<% end %>

		<% if current_user.id == @listing.user_id %>
			<% if @listing.reservations.any? %>
			<table>
				<thead>
					<tr>
						<th>Reservation ID</th>
						<th>User ID</th>
						<th>Check-In Date</th>
						<th>Check-out Date</th>
					</tr>
				</thead>
				<tbody>
				<tr><a href="/listings/<%= @listing.id %>"></a>
				<% @listing.reservations.each do |reservation| %></tr>
				<!-- <h3>Reservation Id | User Id | Check-In Date | Check-Out Date | -->
				<!-- </h3> -->
					<td><a href= "/listings/<%= @listing.id %>/reservations/<%= reservation.id %>"><%= reservation.id %></a>
					</td>
					<td><%= reservation.user.email %></td>
					<td><%= reservation.check_in %></td>
					<td><%= reservation.check_out %></td>
				<% end %>	
			<% end %>		
		<% end %>
	</tbody>
</table>
<%= link_to "Back to all listings", listings_path %>