config/routes.rb
Rails.application.routes.draw do
  get 'payments/new'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  resources :users, only: [:show, :edit, :update, :destroy] 

  resources :listings do

  resources :reservations, only: [:create , :show]
end
  resources :reservations, only: [] do
    resources :payments, only: [:new, :create]
  end

  

  root 'welcome#index'

end

app/views/layouts/_navbar.html.erb
<nav class="menu">
  <ul class="active">
    <li class="current-item"><%= link_to "Home", root_url %></li>
    <li><%= link_to "Login", sign_in_path %></li>
    <li><%= link_to "Signup", sign_up_path %></li>
    <li><%= link_to "About Us", root_url %></li>
    <li><%= link_to "Listings", listings_path %></li>
    <% if current_user %>
    <li><%= link_to "Profile", "users/#{current_user.id}" %></li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=no, minimum-scale=1, height=device-height, target-densitydpi=device-dpi"/>
<%= include_gon %>
   
  <title>PairBnB</title>
    

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

    <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  
   

</head>
<body>
  <div id="header">
    <% if signed_in? -%>
      <%= button_to ".sign_out", sign_out_path, method: :delete %>
    <% else -%>
      <%= link_to ".sign_in", sign_in_path %>
    <% end -%>
  </div>

  <div id="flash">
    <% flash.each do |key, value| -%>
      <div id="flash_<%= key %>"><%=h value %></div>
    <% end %>
  </div>

  <%= render partial: "layouts/navbar" %>
    <div class="container">
      <%= yield %>
    </div>
    <div class="pusher"></div>
    <div id="footer">
      <ul>
        <li>About Us</li>
        <li>Privacy</li>
        <li>Terms</li>
        <li>Contact Us</li>
        <li>Signup for newsletter</li>
      </ul>
    </div>
  </body>
</html>